/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioWeddingsRouteImport } from './routes/portfolio.weddings'
import { Route as PortfolioPortraitsRouteImport } from './routes/portfolio.portraits'
import { Route as PortfolioCouplesRouteImport } from './routes/portfolio.couples'

const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioWeddingsRoute = PortfolioWeddingsRouteImport.update({
  id: '/portfolio/weddings',
  path: '/portfolio/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioPortraitsRoute = PortfolioPortraitsRouteImport.update({
  id: '/portfolio/portraits',
  path: '/portfolio/portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioCouplesRoute = PortfolioCouplesRouteImport.update({
  id: '/portfolio/couples',
  path: '/portfolio/couples',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/investment': typeof InvestmentRoute
  '/portfolio/couples': typeof PortfolioCouplesRoute
  '/portfolio/portraits': typeof PortfolioPortraitsRoute
  '/portfolio/weddings': typeof PortfolioWeddingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/investment': typeof InvestmentRoute
  '/portfolio/couples': typeof PortfolioCouplesRoute
  '/portfolio/portraits': typeof PortfolioPortraitsRoute
  '/portfolio/weddings': typeof PortfolioWeddingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/investment': typeof InvestmentRoute
  '/portfolio/couples': typeof PortfolioCouplesRoute
  '/portfolio/portraits': typeof PortfolioPortraitsRoute
  '/portfolio/weddings': typeof PortfolioWeddingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/investment'
    | '/portfolio/couples'
    | '/portfolio/portraits'
    | '/portfolio/weddings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/investment'
    | '/portfolio/couples'
    | '/portfolio/portraits'
    | '/portfolio/weddings'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/investment'
    | '/portfolio/couples'
    | '/portfolio/portraits'
    | '/portfolio/weddings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  InvestmentRoute: typeof InvestmentRoute
  PortfolioCouplesRoute: typeof PortfolioCouplesRoute
  PortfolioPortraitsRoute: typeof PortfolioPortraitsRoute
  PortfolioWeddingsRoute: typeof PortfolioWeddingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/weddings': {
      id: '/portfolio/weddings'
      path: '/portfolio/weddings'
      fullPath: '/portfolio/weddings'
      preLoaderRoute: typeof PortfolioWeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/portraits': {
      id: '/portfolio/portraits'
      path: '/portfolio/portraits'
      fullPath: '/portfolio/portraits'
      preLoaderRoute: typeof PortfolioPortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/couples': {
      id: '/portfolio/couples'
      path: '/portfolio/couples'
      fullPath: '/portfolio/couples'
      preLoaderRoute: typeof PortfolioCouplesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  InvestmentRoute: InvestmentRoute,
  PortfolioCouplesRoute: PortfolioCouplesRoute,
  PortfolioPortraitsRoute: PortfolioPortraitsRoute,
  PortfolioWeddingsRoute: PortfolioWeddingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
